# -*- coding: utf-8 -*-
"""horizon_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WQSwA_c1M0kyNcstvP9pMHlyCurzmdXa
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from pandas_datareader import data as web
import warnings
warnings.filterwarnings("ignore")
import plotly
import plotly.offline as py
from plotly.offline import plot, iplot
plotly.offline.init_notebook_mode(connected=True)

import plotly.io as pio
pio.renderers
pio.renderers.default = "colab"

import plotly.graph_objs as go
import plotly.graph_objs as go

tick = [str(x+'3.SA').upper() for x in input().split()]

tick

hih = pd.DataFrame()
lw = pd.DataFrame()
opn = pd.DataFrame()
clos = pd.DataFrame()
prices = pd.DataFrame()
tickers = ['ITUB3.SA', 'BBDC3.SA', 'BBAS3.SA', 'SANB3.SA', '^BVSP']
for i in tickers:
    prices[i] = web.get_data_yahoo(i,'01/01/2008')['Adj Close']
    lw[i] = web.get_data_yahoo(i, '01/01/2008')['Low']
    hih[i] = web.get_data_yahoo(i, '01/01/2008')['High']
    opn[i] = web.get_data_yahoo(i, '01/01/2008')['Open']
    clos[i] = web.get_data_yahoo(i, '01/01/2008')['Close']

prices.rename(columns ={'ITUB3.SA':'ITUB', 'BBDC3.SA':'BBDC','BBAS3.SA':'BBAS','SANB3.SA':'SANB', '^BVSP':'IBOV'},inplace = True)
prices['IBOV'] = prices['IBOV']/1000
prices.reset_index(inplace = True)
prices.dropna(subset = ['IBOV'], inplace = True)

tickers = list(prices.drop(['Date'], axis = 1).columns)
plt.figure(figsize=(16,6))

prices

for i in tickers:
        plt.plot(prices['Date'], prices[i])
plt.legend(tickers)
plt.grid()
plt.title("Cotação x tempo", fontsize = 25)
plt.show()

data = []
for i in tickers: 
    close = go.Scatter(
    x=prices.Date,
    y=prices[i],
    name = i,
    #title = teste,
    opacity = 0.8)
    
    data.append(close)

layout = dict(
title="Série com Rangeslider e Botoes",
title_x=0.5,
xaxis=dict(
rangeselector=dict(
buttons=list([
dict(count=1,
label='1m',
step='month',
stepmode='backward'),
dict(count=6,
label='6m',
step='month',
stepmode='backward'),
dict(step='all')
])
),
rangeslider=dict(
visible = False
),
type='date'
)
)

fig = dict(data=data, layout=layout)
py.iplot(fig)

sns.heatmap(prices.corr(), annot = True)
plt.show()

trace = go.Candlestick(x=prices['Date'],
open=opn['ITUB3.SA'],
high=hih['ITUB3.SA'],
low=lw['ITUB3.SA'],
close=clos['ITUB3.SA'])

layout = go.Layout(
title ='Preços em Candlesticks',
title_x = 0.5,
xaxis=dict(
rangeselector=dict(
buttons=list([
dict(count=1,
label='1m',
step='month',
stepmode='backward'),
dict(count=6,
label='6m',
step='month',
stepmode='backward'),
dict(step='all')
])
),
rangeslider=dict(
visible = False
),
type='date'
)
)

data = [trace]

fig = go.Figure(data=data,layout=layout)
py.iplot(fig)

hih

def sep():
  print('blabla')

sep()

